{% set version = "0.18" %}
{% set posix = 'm2-' if win else '' %}
{% set native = 'm2w64-' if win else '' %}

package:
  name: r-servr
  version: {{ version|replace("-", "_") }}

source:
  url:
    - {{ cran_mirror }}/src/contrib/servr_{{ version }}.tar.gz
    - {{ cran_mirror }}/src/contrib/Archive/servr/servr_{{ version }}.tar.gz
  sha256: 4ade7860ecbe854d9f9dcf9e71837b670be17026b96549ba5e900c1e5470cb75

build:
  merge_build_host: true  # [win]
  number: 0
  noarch: generic
  rpaths:
    - lib/R/lib/
    - lib/

requirements:
  build:
    - {{ posix }}zip               # [win]
  host:
    - r-base
    - r-httpuv >=1.4.0
    - r-jsonlite
    - r-mime >=0.2
    - r-xfun
  run:
    - r-base
    - r-httpuv >=1.4.0
    - r-jsonlite
    - r-mime >=0.2
    - r-xfun

test:
  commands:
    - $R -e "library('servr')"           # [not win]
    - "\"%R%\" -e \"library('servr')\""  # [win]

about:
  home: https://github.com/yihui/servr
  license: GPL
  summary: Start an HTTP server in R to serve static files, or dynamic documents that can be converted to HTML files (e.g., R Markdown) under a given directory.
  license_family: GPL
  license_file: {{ environ["PREFIX"] }}/lib/R/share/licenses/GPL-3

extra:
  recipe-maintainers:
    - conda-forge/r

# Package: servr
# Type: Package
# Title: A Simple HTTP Server to Serve Static Files or Dynamic Documents
# Version: 0.14
# Authors@R: c( person("Yihui", "Xie", role = c("aut", "cre"), email = "xie@yihui.name", comment = c(ORCID = "0000-0003-0645-5666")), person("Carson", "Sievert", role = "ctb"), person("Jesse", "Anderson", role = "ctb"), person("Ramnath", "Vaidyanathan", role = "ctb"), person() )
# Maintainer: Yihui Xie <xie@yihui.name>
# Description: Start an HTTP server in R to serve static files, or dynamic documents that can be converted to HTML files (e.g., R Markdown) under a given directory.
# Depends: R (>= 3.0.0)
# Imports: mime (>= 0.2), httpuv (>= 1.4.0), xfun, jsonlite
# Suggests: tools, later, rstudioapi, knitr (>= 1.9), rmarkdown
# License: GPL
# URL: https://github.com/yihui/servr
# BugReports: https://github.com/yihui/servr/issues
# Encoding: UTF-8
# RoxygenNote: 6.1.1
# NeedsCompilation: no
# Packaged: 2019-06-11 20:07:13 UTC; yihui
# Author: Yihui Xie [aut, cre] (<https://orcid.org/0000-0003-0645-5666>), Carson Sievert [ctb], Jesse Anderson [ctb], Ramnath Vaidyanathan [ctb]
# Repository: CRAN
# Date/Publication: 2019-06-11 20:30:03 UTC
